version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: rate_limiter_redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  rate_limiter_app:
    build: .
    container_name: rate_limiter_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx-1
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rate_limiter_app